name: Hostapd AP
version: "0.9.4"
slug: hostapd
description: >-
  WiFi access point managed via a built-in web UI.
  Supports separate 2.4 GHz and 5 GHz radios. Requires adapters with AP mode support.
url: https://github.com/timmchugh11/haos-addons
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
  - i386
startup: services
boot: manual
init: false

host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN

ingress: true
ingress_port: 8080
panel_icon: mdi:wifi
panel_title: WiFi AP
